color: null
description: 'Content model for the About Us single entry.'
fieldLayouts:
  c40cf2e3-10d3-4b9a-9e2e-9869965e5a33:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-19T08:30:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d1fe306-829d-4ea4-a5ec-14ebbfe07738
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c9b7f8b9-6d0f-4b5e-899c-1461d8d26f02 # Body Copy
            handle: null
            includeInCards: false
            instructions: 'Rich descriptive copy for the About page.'
            label: 'Body Copy'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4dd969b-7d7b-4a7a-9f91-1d31c28f744e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f3fb4e3-16de-43c1-a491-4c61bf0de170 # images
            handle: null
            includeInCards: false
            instructions: 'Optional gallery images for the About page.'
            label: Images
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a21bed8b-3ffc-4c27-9b73-bb0f3a46491c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ce59ef4-4f2c-4e24-a9eb-69a9a98f663e
        userCondition: null
handle: aboutPage
hasTitleField: true
icon: null
name: 'About Page'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
