color: red
description: null
fieldLayouts:
  5d2efa77-1ba0-4d68-bea2-ca9f1b821eab:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-19T07:01:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f3fb4e3-16de-43c1-a491-4c61bf0de170 # images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9830522e-6b1b-4820-9374-99ad3ef5df59
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ff6f28e-ae6f-4041-82be-cfdcc4acb695
        userCondition: null
handle: images
hasTitleField: false
icon: null
name: images
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
