altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a229775c-b05c-4b4b-9656-d9275a7b5662:
    cardThumbAlignment: start
    cardView:
      - dateUpdated
      - imageSize
      - link
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-19T07:01:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9ff785c0-d8cc-4438-bccf-dde160ac2ac5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fd47f7b2-da77-4f57-87c2-f06eae7b63ef
        userCondition: null
fs: main_filesystem
handle: thumbnail
name: thumbnail
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
