columnSuffix: null
handle: bodyCopy
instructions: 'Main body text for the About Us page.'
name: 'Body Copy'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 6
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
